### PR TITLE
correct typos

### PR DESCRIPTION
**Pull request by mannynotfound**
can we hang out

### CODE REVIEW

**Comment by ptsteadman** [comment]
Yeah that's a really good idea, I was thinking the same thing

**Comment by ptsteadman** [comment]
Later this week ?

**Comment by mannynotfound** [comment]
# in DM

**Comment by maryburford** [comment]
Suck a dick dudes

**Comment by maryburford** [comment]
@nikolas mind your own business.

**Comment by nikolas** [comment]
ii'm sorry

**Comment by Sjneugent** [comment]
@nikolas you're good man.  You do you.

**Comment by ptsteadman** [comment]
Manny I miss you

**Pull request merged**
